import { useState } from "react";
import { Link, NavLink, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { BriefcaseBusiness, Search, MapPin, ArrowUpRight, Sparkles, Users, Building2, Clock3, Menu, X, LayoutDashboard, Plus, LogOut, ChevronRight, CheckCircle2 } from "lucide-react";
import api from "./api";
import { useAuth } from "./context/AuthContext";

const demoJobs = [
 { _id:"demo1", title:"Frontend Developer", company:"PixelCraft Studio", location:"New Delhi, India", type:"Full-time", workplace:"Hybrid", salary:"₹6–10 LPA", description:"Build polished, accessible user experiences with React. Collaborate with design and backend teams to ship reliable features.", skills:["React","JavaScript","CSS"], createdAt:new Date().toISOString() },
 { _id:"demo2", title:"Data Analyst Intern", company:"Northstar Analytics", location:"Remote", type:"Internship", workplace:"Remote", salary:"₹18k–25k / month", description:"Turn business data into clear insights. Prepare dashboards, clean datasets, and communicate findings to stakeholders.", skills:["SQL","Excel","Power BI"], createdAt:new Date().toISOString() },
 { _id:"demo3", title:"Node.js Backend Engineer", company:"Orbit Fintech", location:"Bengaluru, India", type:"Full-time", workplace:"On-site", salary:"₹10–16 LPA", description:"Design REST APIs and scalable services using Node.js and MongoDB. Write maintainable code and tests.", skills:["Node.js","Express","MongoDB"], createdAt:new Date().toISOString() },
 { _id:"demo4", title:"Product Design Associate", company:"Goodform", location:"Mumbai, India", type:"Full-time", workplace:"Hybrid", salary:"₹7–12 LPA", description:"Help make complex workflows feel simple through research, prototyping, and thoughtful interface design.", skills:["Figma","UX Research","Prototyping"], createdAt:new Date().toISOString() },
 { _id:"demo5", title:"QA Automation Trainee", company:"Cloudlane Systems", location:"Noida, India", type:"Full-time", workplace:"On-site", salary:"₹4–6 LPA", description:"Create and maintain automated test cases, report bugs, and partner with engineers to improve product quality.", skills:["Testing","JavaScript","Playwright"], createdAt:new Date().toISOString() },
 { _id:"demo6", title:"Digital Marketing Executive", company:"Bloom & Co.", location:"Remote", type:"Contract", workplace:"Remote", salary:"₹35k–50k / month", description:"Plan campaigns, monitor performance, and test content that helps a growing digital brand reach new customers.", skills:["SEO","Analytics","Content"], createdAt:new Date().toISOString() }
];
function Logo(){return <Link className="logo" to="/"><span className="logo-mark"><BriefcaseBusiness size={19}/></span>hireflow<span className="logo-dot">.</span></Link>}
function Header(){
 const {user,logout}=useAuth(); const [open,setOpen]=useState(false);
 return <header className="header"><div className="nav-wrap"><Logo/><button className="mobile-toggle icon-btn" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button><nav className={open?"nav-links open":"nav-links"}><NavLink to="/jobs">Find jobs</NavLink>{user&&<NavLink to={user.role==="recruiter"?"/dashboard":"/applications"}>{user.role==="recruiter"?"Recruiter dashboard":"My applications"}</NavLink>}{user?.role==="recruiter"&&<Link className="nav-post" to="/post-job"><Plus size={16}/> Post a job</Link>}{user?<><span className="nav-user">Hi, {user.name.split(" ")[0]}</span><button className="text-btn" onClick={logout}><LogOut size={15}/> Log out</button></>:<><Link to="/login" className="text-btn">Log in</Link><Link to="/register" className="btn btn-small">Get started <ArrowUpRight size={15}/></Link></>}</nav></div></header>
}
function Footer(){return <footer className="footer"><div className="container footer-inner"><Logo/><span>Made for the next step in your career.</span><span>© 2026 HireFlow</span></div></footer>}
function JobCard({job}){return <Link className="job-card" to={`/jobs/${job._id}`}><div className="job-top"><div className="company-logo">{job.company?.slice(0,1)||"H"}</div><span className="job-type">{job.type}</span></div><h3>{job.title}</h3><p className="company-name">{job.company}</p><div className="job-meta"><span><MapPin size={14}/>{job.location}</span><span><Building2 size={14}/>{job.workplace||"On-site"}</span></div><div className="job-bottom"><strong>{job.salary||"Salary not disclosed"}</strong><span className="card-arrow"><ArrowUpRight size={17}/></span></div></Link>}
function Home(){
 const [q,setQ]=useState(""); const [location,setLocation]=useState(""); const [jobs,setJobs]=useState(demoJobs); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const search=async(e)=>{e?.preventDefault();setLoading(true);setError("");try{const {data}=await api.get("/jobs",{params:{q,location}});setJobs(data.jobs.length?data.jobs:[]);}catch{setJobs(demoJobs.filter(j=>(!q||`${j.title} ${j.company} ${j.skills.join(" ")}`.toLowerCase().includes(q.toLowerCase()))&&(!location||j.location.toLowerCase().includes(location.toLowerCase()))));setError("Showing sample jobs because the API is not connected yet.");}finally{setLoading(false);}};
 return <><section className="hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="container hero-content"><div className="eyebrow"><Sparkles size={14}/> YOUR NEXT CHAPTER STARTS HERE</div><h1>Find work that<br/><span>moves you forward.</span></h1><p className="hero-copy">Great opportunities don't happen by chance. Find the role that fits your ambition and make your next move with confidence.</p><form className="search-panel" onSubmit={search}><label className="search-field"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Job title, skill, or company"/></label><span className="search-divider"/><label className="search-field"><MapPin size={20}/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="City or remote"/></label><button className="btn search-btn" type="submit">{loading?"Searching…":"Search jobs"} <ArrowUpRight size={17}/></button></form><div className="hero-foot"><span><CheckCircle2 size={15}/> Curated opportunities</span><span><CheckCircle2 size={15}/> Roles for every stage</span><span><CheckCircle2 size={15}/> Your next step, simplified</span></div></div></section>
 <section className="container jobs-section"><div className="section-heading"><div><div className="eyebrow muted">THE RIGHT OPPORTUNITY</div><h2>Explore open roles<span className="accent">.</span></h2><p>Handpicked roles to help you do your best work.</p></div><Link to="/jobs" className="view-all">View all jobs <ArrowUpRight size={16}/></Link></div>{error&&<p className="notice">{error}</p>}<div className="jobs-grid">{jobs.slice(0,6).map(j=><JobCard key={j._id} job={j}/>)}</div>{!jobs.length&&<div className="empty-state">No matching jobs found. Try a different search.</div>}<div className="center-action"><Link to="/jobs" className="btn btn-outline">Explore all opportunities <ChevronRight size={17}/></Link></div></section>
 <section className="cta-band"><div className="container cta-inner"><div className="cta-icon"><Users size={26}/></div><div><h2>Building a team?</h2><p>Meet people who are ready to make an impact. Share your opening with the HireFlow community.</p></div><Link to="/register" className="btn btn-light">Hire with HireFlow <ArrowUpRight size={17}/></Link></div></section></>
}
function JobsPage(){const [jobs,setJobs]=useState([]),[q,setQ]=useState(""),[loc,setLoc]=useState(""),[type,setType]=useState("");const [loading,setLoading]=useState(true);const [err,setErr]=useState("");
 const load=async()=>{setLoading(true);try{const {data}=await api.get("/jobs",{params:{q,location:loc,type}});setJobs(data.jobs);setErr("");}catch{setJobs(demoJobs.filter(j=>(!q||`${j.title} ${j.company} ${j.skills.join(" ")}`.toLowerCase().includes(q.toLowerCase()))&&(!loc||j.location.toLowerCase().includes(loc.toLowerCase()))&&(!type||j.type===type)));setErr("Sample listings are shown until the backend is connected.");}finally{setLoading(false);}};
 useState(()=>{load()},[]);
 return <main className="container page"><div className="page-heading"><div className="eyebrow muted">YOUR SEARCH STARTS HERE</div><h1>Find your next role<span className="accent">.</span></h1><p>Search roles, discover teams, and take the next step.</p></div><form className="filter-bar" onSubmit={e=>{e.preventDefault();load()}}><label><Search size={18}/><input placeholder="Role, skill, company" value={q} onChange={e=>setQ(e.target.value)}/></label><label><MapPin size={18}/><input placeholder="Location" value={loc} onChange={e=>setLoc(e.target.value)}/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="">All job types</option>{["Full-time","Part-time","Contract","Internship","Remote"].map(t=><option key={t}>{t}</option>)}</select><button className="btn">Search</button></form>{err&&<p className="notice">{err}</p>}<div className="results-head"><strong>{loading?"Loading…":`${jobs.length} opportunities`}</strong><span>Newest listings first</span></div><div className="jobs-grid">{jobs.map(j=><JobCard key={j._id} job={j}/>)}</div>{!loading&&!jobs.length&&<div className="empty-state">No jobs match those filters. Try broadening your search.</div>}</main>
}
function JobDetail(){const {id}=useParams();const {user}=useAuth();const [job,setJob]=useState(null);const [cover,setCover]=useState("");const [msg,setMsg]=useState("");const [loading,setLoading]=useState(true);
 useState(()=>{if(id.startsWith("demo")){setJob(demoJobs.find(j=>j._id===id)||demoJobs[0]);setLoading(false);}else api.get(`/jobs/${id}`).then(r=>setJob(r.data.job)).catch(()=>setMsg("This job could not be loaded. Make sure the backend is running.")).finally(()=>setLoading(false));},[id]);
 const apply=async()=>{if(!user)return window.location.assign("/login");try{const {data}=await api.post(`/jobs/${id}/apply`,{coverLetter:cover});setMsg(data.message||"Application submitted!");}catch(e){setMsg(e.response?.data?.message||"Could not submit application.");}};
 if(loading)return <main className="container page">Loading job…</main>;if(!job)return <main className="container page"><p>{msg||"Job not found."}</p></main>;
 return <main className="container page detail-layout"><article className="detail-main"><Link to="/jobs" className="back-link">← Back to jobs</Link><div className="detail-company"><div className="company-logo large">{job.company?.slice(0,1)}</div><div><h1>{job.title}</h1><p>{job.company} · {job.location}</p></div></div><div className="tag-row"><span className="job-type">{job.type}</span><span className="job-type">{job.workplace||"On-site"}</span></div><h2>About this role</h2><p className="description">{job.description}</p><h2>Skills you'll use</h2><div className="skill-list">{(job.skills||[]).map(s=><span key={s}>{s}</span>)}</div>{user?.role==="candidate"&&job._id&&!job._id.startsWith("demo")&&<div className="apply-box"><h2>Apply for this role</h2><textarea value={cover} onChange={e=>setCover(e.target.value)} placeholder="Optional: introduce yourself and share why you're a good fit."/><button className="btn" onClick={apply}>Submit application <ArrowUpRight size={16}/></button></div>}{msg&&<p className="notice">{msg}</p>}</article><aside className="detail-aside"><div className="apply-card"><div className="eyebrow muted">ROLE SNAPSHOT</div><h2>{job.salary||"Salary not disclosed"}</h2><p>Compensation</p><hr/><div className="snapshot-line"><MapPin size={17}/><span><b>Location</b><br/>{job.location}</span></div><div className="snapshot-line"><Clock3 size={17}/><span><b>Employment</b><br/>{job.type}</span></div><div className="snapshot-line"><Building2 size={17}/><span><b>Work style</b><br/>{job.workplace||"On-site"}</span></div>{job._id.startsWith("demo")?<p className="small-muted">Sample listing — connect MongoDB and use a real listing to apply.</p>:user?.role==="candidate"?<button className="btn full" onClick={apply}>Apply now <ArrowUpRight size={16}/></button>:!user?<Link className="btn full" to="/login">Log in to apply</Link>:<p className="small-muted">Candidate accounts can apply to this role.</p>}</div></aside></main>
}
function AuthPage({mode}){const {login,register}=useAuth();const navigate=useNavigate();const [form,setForm]=useState({name:"",email:"",password:"",role:"candidate"});const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();setError("");setBusy(true);try{const user=mode==="login"?await login({email:form.email,password:form.password}):await register(form);navigate(user.role==="recruiter"?"/dashboard":"/jobs");}catch(e){setError(e.response?.data?.message||"Could not connect. Check that the backend is running.");}finally{setBusy(false);}};
 return <main className="auth-wrap"><div className="auth-card"><Link to="/" className="back-link">← Back home</Link><div className="auth-icon"><BriefcaseBusiness size={25}/></div><h1>{mode==="login"?"Welcome back":"Your next chapter starts here"}</h1><p>{mode==="login"?"Log in to continue your HireFlow journey.":"Create your free account and find your next opportunity."}</p><form onSubmit={submit} className="auth-form">{mode==="register"&&<><label>Full name<input name="name" required value={form.name} onChange={change} placeholder="e.g. Aanya Sharma"/></label><label>I want to<select name="role" value={form.role} onChange={change}><option value="candidate">Find a job (Candidate)</option><option value="recruiter">Hire talent (Recruiter)</option></select></label></>}<label>Email address<input name="email" type="email" required value={form.email} onChange={change} placeholder="you@example.com"/></label><label>Password<input name="password" type="password" minLength="8" required value={form.password} onChange={change} placeholder="At least 8 characters"/></label>{error&&<p className="form-error">{error}</p>}<button className="btn full" disabled={busy}>{busy?"Please wait…":mode==="login"?"Log in":"Create account"} <ArrowUpRight size={16}/></button></form><p className="auth-switch">{mode==="login"?"New to HireFlow?":"Already have an account?"} <Link to={mode==="login"?"/register":"/login"}>{mode==="login"?"Create an account":"Log in"}</Link></p></div></main>
}
function Protected({children,role}){const {user,loading}=useAuth();if(loading)return <main className="container page">Loading account…</main>;if(!user)return <AuthPage mode="login"/>;if(role&&user.role!==role)return <main className="container page"><div className="empty-state">This page is not available for your account type.</div></main>;return children;}
function PostJob(){const navigate=useNavigate();const [form,setForm]=useState({title:"",company:"",location:"",type:"Full-time",workplace:"Hybrid",salary:"",description:"",skills:""});const [error,setError]=useState("");const [busy,setBusy]=useState(false);const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{await api.post("/jobs",form);navigate("/dashboard");}catch(e){setError(e.response?.data?.message||"Unable to publish job.");}finally{setBusy(false);}};
 return <main className="container page form-page"><div className="page-heading"><div className="eyebrow muted">GROW YOUR TEAM</div><h1>Post a new role<span className="accent">.</span></h1><p>Help the right candidate discover their next opportunity.</p></div><form className="panel-form" onSubmit={submit}><div className="form-grid"><label>Job title *<input name="title" required value={form.title} onChange={change} placeholder="e.g. Frontend Developer"/></label><label>Company name *<input name="company" required value={form.company} onChange={change} placeholder="Your company"/></label><label>Location *<input name="location" required value={form.location} onChange={change} placeholder="City or Remote"/></label><label>Job type<select name="type" value={form.type} onChange={change}>{["Full-time","Part-time","Contract","Internship","Remote"].map(x=><option key={x}>{x}</option>)}</select></label><label>Work style<select name="workplace" value={form.workplace} onChange={change}>{["On-site","Hybrid","Remote"].map(x=><option key={x}>{x}</option>)}</select></label><label>Salary range<input name="salary" value={form.salary} onChange={change} placeholder="e.g. ₹6–10 LPA"/></label></div><label>Job description *<textarea name="description" required minLength="20" value={form.description} onChange={change} placeholder="Describe the role, responsibilities, and ideal candidate…"/></label><label>Skills (comma-separated)<input name="skills" value={form.skills} onChange={change} placeholder="React, JavaScript, Communication"/></label>{error&&<p className="form-error">{error}</p>}<button className="btn" disabled={busy}>{busy?"Publishing…":"Publish job"} <ArrowUpRight size={16}/></button></form></main>
}
function Dashboard(){const [data,setData]=useState({applications:[],jobsCount:0});const [error,setError]=useState("");const load=()=>api.get("/applications/recruiter").then(r=>setData(r.data)).catch(e=>setError(e.response?.data?.message||"Could not load dashboard."));useState(()=>{load()},[]);
 const update=async(id,status)=>{try{await api.patch(`/applications/${id}/status`,{status});load();}catch(e){setError(e.response?.data?.message||"Could not update status.");}};
 return <main className="container page"><div className="dashboard-heading"><div><div className="eyebrow muted">RECRUITER WORKSPACE</div><h1>Your hiring dashboard<span className="accent">.</span></h1><p>Manage your roles and meet your next great teammate.</p></div><Link to="/post-job" className="btn"><Plus size={17}/> Post a job</Link></div>{error&&<p className="notice">{error}</p>}<div className="stat-grid"><div className="stat-card"><span>Active job posts</span><strong>{data.jobsCount}</strong><BriefcaseBusiness/></div><div className="stat-card"><span>Total applications</span><strong>{data.applications.length}</strong><Users/></div><div className="stat-card"><span>Shortlisted</span><strong>{data.applications.filter(a=>a.status==="Shortlisted").length}</strong><CheckCircle2/></div></div><div className="table-panel"><div className="table-title"><h2>Recent applications</h2><span>{data.applications.length} total</span></div>{!data.applications.length?<div className="empty-state compact">No applications yet. Post a role to get started.</div>:<div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Role</th><th>Applied</th><th>Status</th></tr></thead><tbody>{data.applications.map(a=><tr key={a._id}><td><b>{a.candidate?.name}</b><small>{a.candidate?.email}</small></td><td>{a.job?.title}</td><td>{new Date(a.createdAt).toLocaleDateString()}</td><td><select className="status-select" value={a.status} onChange={e=>update(a._id,e.target.value)}>{["Submitted","In Review","Shortlisted","Rejected"].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>}</div></main>
}
function Applications(){const [apps,setApps]=useState([]);const [error,setError]=useState("");useState(()=>{api.get("/applications/mine").then(r=>setApps(r.data.applications)).catch(e=>setError(e.response?.data?.message||"Could not load applications."));},[]);
 return <main className="container page"><div className="page-heading"><div className="eyebrow muted">YOUR CAREER JOURNEY</div><h1>My applications<span className="accent">.</span></h1><p>Keep track of every opportunity you've pursued.</p></div>{error&&<p className="notice">{error}</p>}<div className="application-list">{apps.map(a=><div className="application-item" key={a._id}><div className="company-logo">{a.job?.company?.slice(0,1)}</div><div className="application-info"><h3>{a.job?.title||"Job listing removed"}</h3><p>{a.job?.company} · {a.job?.location}</p></div><span className={`status-pill ${a.status.toLowerCase().replace(" ","-")}`}>{a.status}</span></div>)}{!apps.length&&!error&&<div className="empty-state">Your applications will appear here once you apply to a role.</div>}</div></main>
}
export default function App(){const {user}=useAuth();return <><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/jobs" element={<JobsPage/>}/><Route path="/jobs/:id" element={<JobDetail/>}/><Route path="/login" element={<AuthPage mode="login"/>}/><Route path="/register" element={<AuthPage mode="register"/>}/><Route path="/post-job" element={<Protected role="recruiter"><PostJob/></Protected>}/><Route path="/dashboard" element={<Protected role="recruiter"><Dashboard/></Protected>}/><Route path="/applications" element={<Protected role="candidate"><Applications/></Protected>}/><Route path="*" element={<main className="container page"><div className="empty-state">Page not found. <Link to="/">Go home</Link></div></main>}/></Routes><Footer/></>}
